version: '3.5'

services:
  server:
    image: example-server
    container_name: server
    ports:
      - 50051:50051

  client:
    image: example-client
    container_name: client
    command: ["server:50051","client"]
    volumes:
      - ./json:/data/json